apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: aws-rds
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: awsrds.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      names:
        kind: AWSRDS
        plural: awsrds
        singular: awsrds
        shortNames:
          - awsrds
      scope: Namespaced
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    namespace:
                      default: default
                      description: Kubernetes namespace to create aws rds instance.
                      type: string
                    name:
                      type: string
                      description: AWS RDS instance name
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
            namespace: default
          spec:
            containers:
              - image: 533267353680.dkr.ecr.eu-west-2.amazonaws.com/aws-rds-configure-pipeline:v0.1.0
                name: aws-rds-promise-pipeline
                imagePullPolicy: Always
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: 533267353680.dkr.ecr.eu-west-2.amazonaws.com/aws-rds-configure-pipeline:v0.1.0
                name: aws-rds-instance-promise-pipeline
                imagePullPolicy: Always